name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_fmt_clippy:
    name: Fmt & Clippy Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust (rustup)
        run: |
          rustup update stable --no-self-update
          rustup default stable
          rustup component add rustfmt
          rustup component add clippy
      - name: Build
        run: cargo build --verbose
      - name: Format Check
        run: |
          cargo fmt --version
          cargo fmt -- --check --verbose
      - name: Clippy Check
        run: |
          cargo clippy
          cargo clippy --version
          cargo clippy -- --verbose -D warnings

  build_ubuntu:
    name: Ubuntu Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust (rustup)
      run: |
        rustup update stable --no-self-update
        rustup default stable
    - name: Test
      run: cargo test --verbose
    - name: Build Release
      run: cargo build --release --verbose
    - name: Move Artifacts
      run: |
        ls target/release
        cp target/release/rustyhack_client rustyhack-client
        ls target/release
        cp target/release/rustyhack_server rustyhack-server
        chmod +x rustyhack-client
        chmod +x rustyhack-server
        tar -cvzf rustyhack-client-ubuntu.tar.gz rustyhack-client
        tar -cvzf rustyhack-server-ubuntu.tar.gz rustyhack-server assets
    - name: Upload Artifact Client
      uses: actions/upload-artifact@v4
      with:
        name: rustyhack-client-ubuntu
        path: rustyhack-client-ubuntu.tar.gz
    - name: Upload Artifact Server
      uses: actions/upload-artifact@v4
      with:
        name: rustyhack-server-ubuntu
        path: rustyhack-server-ubuntu.tar.gz

  build_macos:
    name: Mac Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust (rustup)
        run: |
          rustup update stable --no-self-update
          rustup default stable
      - name: Test
        run: cargo test --verbose
      - name: Build Release
        run: cargo build --release --verbose
      - name: Move Artifacts
        run: |
          cp target/release/rustyhack_client rustyhack-client
          cp target/release/rustyhack_server rustyhack-server
          chmod +x rustyhack-client
          chmod +x rustyhack-server
          tar -cvzf rustyhack-client-macos.tar.gz rustyhack-client
          tar -cvzf rustyhack-server-macos.tar.gz rustyhack-server assets
      - name: Upload Artifact Client
        uses: actions/upload-artifact@v4
        with:
          name: rustyhack-client-macos
          path: rustyhack-client-macos.tar.gz
      - name: Upload Artifact Server
        uses: actions/upload-artifact@v4
        with:
          name: rustyhack-server-macos
          path: rustyhack-server-macos.tar.gz

  build_win32:
    name: Win32 Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust (rustup)
        run: |
          rustup update stable-i686 --no-self-update
          rustup default stable-i686
      - name: Test
        run: cargo test --verbose
      - name: Build Release
        run: cargo build --release --verbose
      - name: Move Artifacts
        run: |
          copy target\release\rustyhack_client.exe rustyhack-client.exe
          copy target\release\rustyhack_server.exe rustyhack-server.exe
      - name: Upload Artifact Client (win32)
        uses: actions/upload-artifact@v4
        with:
          name: rustyhack-client-win32
          path: rustyhack-client.exe
      - name: Upload Artifact Server (win32)
        uses: actions/upload-artifact@v4
        with:
          name: rustyhack-server-win32
          path: |
            rustyhack-server.exe
            assets\**\*

  build_win64:
    name: Win64 Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust (rustup)
        run: |
          rustup update stable-x86_64 --no-self-update
          rustup default stable-x86_64
      - name: Test
        run: cargo test --verbose
      - name: Build Release
        run: cargo build --release --verbose
      - name: Move Artifacts
        run: |
          copy target\release\rustyhack_client.exe rustyhack-client.exe
          copy target\release\rustyhack_server.exe rustyhack-server.exe
      - name: Upload Artifact Client (win64)
        uses: actions/upload-artifact@v4
        with:
          name: rustyhack-client-win64
          path: rustyhack-client.exe
      - name: Upload Artifact Server (win64)
        uses: actions/upload-artifact@v4
        with:
          name: rustyhack-server-win64
          path: |
            rustyhack-server.exe
            assets\**\*

  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
